config/routes.rb
Rails.application.routes.draw do
  concern :likeable do
    resource :likes, only: [ :create, :destroy ]
  end

  resources :posts, concerns: :likeable do
    resources :comments, except: [ :index, :show ], concerns: :likeable
  end

  resources :categories, except: :show
  resource :session
  resources :passwords, param: :token

  resources :registrations, only: [ :new, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Likeable

  belongs_to :user
  belongs_to :post

  MAX_CONTENT_LENGTH = 256
  validates :content, presence: true, length: { maximum: MAX_CONTENT_LENGTH }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [ :edit, :update, :destroy ]
  before_action :set_comment, only: [ :edit, :update, :destroy ]

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = Current.user

    if @comment.save
      respond_to do |format|
        flash[:notice] = "Comment created successfully"
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post), notice: "Comment updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @comment.destroy
      redirect_to post_comments_path(@post), notice: "Comment deleted successfully"
    else
      redirect_to post_comments_path(@post), alert: @comment.errors.full_messages.join(", ")
    end
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    def comment_params
      params.expect(comment: [ :content ])
    end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
  <div class="flex justify-between rounded-md border border-gray-400 px-4 py-3 gap-2">
    <div class="flex flex-col gap-2">
      <p class="text-gray-500"><%= comment.content %></p>
      <p class="text-gray-500 text-sm font-normal"><%= time_ago_in_words comment.created_at %> ago</p>
    </div>

    <div class="flex items-center gap-2">
      <%= render "likes", likeable: comment %>

      <% if authenticated_and_authorized?(comment) %>
        <%= link_to "Edit", edit_post_comment_path(comment.post, comment), class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
        <%= button_to "Delete", post_comment_path(comment.post, comment), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "rounded-md px-3.5 py-2.5 bg-red-600 hover:bg-red-500 text-white block font-medium cursor-pointer" %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ post, comment ],
            class: "flex flex-col gap-4",
            data: {
              controller: "form",
              action: "turbo:submit-end->form#reset"
            } do |form| %>
  <%= render "form_errors", record: form.object %>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium cursor-pointer" %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend :comments, @comment %>
<% turbo_stream.replace :comments_form do %>
  <%= turbo_frame_tag :comments_form,
                          src: new_post_comment_path(@post),
                          loading: :lazy %>
<% end %>

app/views/comments/edit.html.erb
<div class="flex flex-col gap-4 w-full">
  <div class="flex justify-between items-center w-full">
    <h1 class="font-bold text-4xl">Comment Edit</h1>

    <%= link_to "Back", post_path(@post), class: "rounded-md px-3.5 py-2.5 bg-green-600 hover:bg-green-500 text-white block font-medium" %>
  </div>

  <%= render "form", post: @post, comment: @comment %>
</div>

app/views/comments/new.html.erb
  <div class="flex flex-col gap-4 w-full">
    <div class="flex justify-between items-center w-full">
      <h1 class="font-bold text-4xl">Comment New</h1>

      <%= link_to "Back", post_path(@post), class: "rounded-md px-3.5 py-2.5 bg-green-600 hover:bg-green-500 text-white block font-medium" %>
    </div>

    <%= turbo_frame_tag :comments_form do %>
      <%= render "form", post: @post, comment: @comment %>
    <% end %>
  </div>