config/routes.rb
Rails.application.routes.draw do
  concern :likeable do
    resource :likes, only: [ :create, :destroy ]
  end

  resources :posts, concerns: :likeable do
    resources :comments, except: [ :index, :show ], concerns: :likeable
  end

  resources :categories, except: :show
  resource :session
  resources :passwords, param: :token

  resources :registrations, only: [ :new, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [ :edit, :update, :destroy ]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "Category successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: "Category successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @category.destroy
      redirect_to categories_path, notice: "Category successfully deleted"
    else
      redirect_to categories_path, alert: @category.errors.full_messages.join(", ")
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.expect(category: [ :title ])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  # def deneme(name, key: "")
  #   "DENEME" + "-" + name + "-" + key
  # end
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>"
     class="flex justify-between rounded-md border border-gray-400 px-4 py-3 gap-2">
  <div class="flex items-center justify-between gap-1 flex-1">
    <p><%= category.title %></p>
    <p class="text-gray-500 text-sm font-normal"><%= time_ago_in_words category.created_at %> ago</p>
  </div>

  <div class="flex gap-2">
    <%= link_to "Edit",
                edit_category_path(category),
                class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
    <%= button_to "Delete",
                  category_path(category),
                  method: :delete,
                  data: { turbo_confirm: "Are you sure?" },
                  class: "rounded-md px-3.5 py-2.5 bg-red-600 hover:bg-red-500 text-white block font-medium cursor-pointer" %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: category, class: "flex flex-col gap-4" do |form| %>
  <%= render "form_errors", record: form.object %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title, autofocus: true, placeholder: true, class: "block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full" %>
  </div>

  <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
<% end %>

app/views/categories/edit.html.erb
<div class="flex flex-col gap-4 w-full">
  <div class="flex justify-between items-center w-full">
    <h1 class="font-bold text-4xl">Category Edit</h1>

    <%= link_to "Back", categories_path, class: "rounded-md px-3.5 py-2.5 bg-green-600 hover:bg-green-500 text-white block font-medium" %>
  </div>

  <%= render "form", category: @category %>
</div>

app/views/categories/index.html.erb
<div class="flex flex-col gap-4 w-full">
  <div class="flex justify-between items-center w-full">
    <h1 class="font-bold text-4xl">Categories</h1>

    <%= link_to "New category", new_category_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="categories" class="min-w-full flex flex-col gap-4">
    <% if @categories.any? %>
      <%= render @categories %>
    <% else %>
      <p class="text-center my-10">No categories found.</p>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="flex flex-col gap-4 w-full">
  <div class="flex justify-between items-center w-full">
    <h1 class="font-bold text-4xl">Category New</h1>

    <%= link_to "Back", categories_path, class: "rounded-md px-3.5 py-2.5 bg-green-600 hover:bg-green-500 text-white block font-medium" %>
  </div>

  <%= render "form", category: @category %>
</div>