config/routes.rb
Rails.application.routes.draw do
  concern :likeable do
    resource :likes, only: [ :create, :destroy ]
  end

  resources :posts, concerns: :likeable do
    resources :comments, except: [ :index, :show ], concerns: :likeable
  end

  resources :categories, except: :show
  resource :session
  resources :passwords, param: :token

  resources :registrations, only: [ :new, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rate_limit to: 10, within: 3.minutes, with: -> { redirect_to root_path, alert: "Try again later." }

  include Authentication
  include TurboHelper
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/helpers/application_helper.rb
module ApplicationHelper
  ActionView::Base.default_form_builder = FormBuilder

  def likeable_path(likeable)
    case likeable
    when Post
      post_likes_path(likeable)
    when Comment
      post_comment_likes_path(likeable.post, likeable)
    end
  end
end

app/views/application/_flash_messages.html.erb
<div id="flash_messages" class="flex flex-col items-center justify-center fixed top-2 w-full pointer-events-none">
  <% flash.each do |type, message| %>
    <div class="px-3 py-2 mb-4 <%= type %> rounded-lg text-white font-bold">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/application/_form_errors.html.erb
<ul class="list-disc list-inside">
  <% record.errors.each do |error| %>
    <li class="text-red-500"><%= error.full_message %></li>
  <% end %>
</ul>

app/views/application/_header.html.erb
<header class="flex justify-between items-center container mx-auto px-5 py-4">
  <div class="flex items-center gap-4">
    <h1 class="text-2xl font-bold">
      <%= link_to "Blog", root_path %>
    </h1>

    <% if authenticated? %>
      <span class="text-gray-500 text-sm">
        Welcome, <%= Current.user.email_address %>
      </span>
    <% end %>
  </div>

  <nav class="flex items-center gap-4">
    <%= link_to "Posts", posts_path, class: "text-gray-500 hover:text-gray-700 underline hover:no-underline" %>

    <% if authenticated? %>
      <%= link_to "Categories", categories_path, class: "text-gray-500 hover:text-gray-700 underline hover:no-underline" %>
      <%= button_to "Logout", session_path, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "text-red-500 hover:text-gray-700 underline hover:no-underline cursor-pointer" %>
    <% else %>
      <%= link_to "Login", new_session_path, class: "text-gray-500 hover:text-gray-700 underline hover:no-underline" %>
      <%= link_to "Sign Up", new_registration_path, class: "text-gray-500 hover:text-gray-700 underline hover:no-underline" %>
    <% end %>
  </nav>
</header>

app/views/application/_likes.html.erb
<div id="<%= dom_id(likeable, :likes) %>" class="flex items-center">
  <% if authenticated? %>
    <% if likeable.liked_by?(Current.user) %>
      <%= button_to "Unlike",
                    likeable_path(likeable),
                    method: :delete,
                    class: "rounded-l-md px-3.5 py-2.5 bg-red-600 hover:bg-red-500 text-white block font-medium" %>
    <% else %>
      <%= button_to "Like",
                    likeable_path(likeable),
                    method: :post,
                    class: "rounded-l-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
    <% end %>
  <% end %>

  <div class="rounded-r-md px-3.5 py-2.5 bg-green-600 hover:bg-green-500 text-white block font-medium">
    <%= likeable.likes_count %>
  </div>
</div>